### PR TITLE
fix ./example/ to be in sync with ./docs/example.md

### PR DESCRIPTION
**Pull request by ra1u**
./example is modified in a way to be same as docs/example.md

There are some modifications to docs/example.md , particularly to command  protoc that was incompatible with recent versions of protoc.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by wmatveyenko** [comment]
Hi, can you elaborate a bit more on the problem you are seeing? It would be helpful to know what you saw versus what you expected, what version of protoc you were using, etc.

Thanks,
Wade

**Comment by ra1u** [comment]
Runing as per https://twitchtv.github.io/twirp/docs/example.html#generate-code
`protoc --twirp_out=. --go_out=paths=. rpc/haberdasher/service.proto`

returns
`paths=./: No such file or directory`

### Versions:
Installed as per https://twitchtv.github.io/twirp/docs/install.html#install-twirp-and-protobuf-generators
   
    go install github.com/twitchtv/twirp/protoc-gen-twirp@latest
    go install google.golang.org/protobuf/cmd/protoc-gen-go@latest

protoc-gen-go

    protoc-gen-go --version  
    protoc-gen-go v1.28.0

protoc-gen-twirp

    protoc-gen-twirp  --version 
    v8.1.2

[`./check_protoc_version.sh`](https://github.com/twitchtv/twirp/blob/main/check_protoc_version.sh)

    protoc version: libprotoc 3.18.1

**Comment by wmatveyenko** [comment]
Sorry this took so long. Please fix the conflict and then we can merge.

**Comment by wmatveyenko** [comment]
Hi @ra1u, just pinging to see if you still want this PR to be merged.

**Comment by ra1u** [comment]
I am sorry. I can take time to ressurect this in next days or over this weekend.

**Comment by ra1u** [comment]
Main idea here is having coherent example and documentation. I am still not sure this is all correct, so I am looking for someone to take review.

**Comment by wmatveyenko** [comment]
Looks good. Thanks for your contribution!

**Comment by wmatveyenko** [comment]
Hi, we had to revert this change, as the tests failed after this was merged. If you want to resubmit with fixed tests, that would be great.

**Pull request merged**
