### PR TITLE
Forced proto3 OPTIONAL feature flag, deps updated 

### PR DESCRIPTION
**Pull request by Solution**
Hello guys,

i've added support for OPTIONAL feature flag which is coming with new version of [protobuf](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/compiler/code_generator.h#L108), since the twirp it's not generating the .pb files, it doesn't need to implement anything in code generator, so it'll have no impact on gen-twirp. 

Issue: `.proto is a proto3 file that contains optional fields, but code generator protoc-gen-twirp hasn't been updated to support optional fields in proto3. Please ask the owner of this code generator to support proto3 optional.--twirp_out:`

What i did: 
- updated dependencies - it was neccessary for newer version of .pb file of plugin
- add supported feature to plugin response. 

I tried to minimize the impact of upgrading the protobuf deps, but there's lot of changes since the last vendor update.

All tests passing. 

//edit: 
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by marioizquierdo** [comment]
Is this related to issue #222 ?

**Comment by Solution** [comment]
@marioizquierdo hello, sorry for the delay. It's related to: https://github.com/protocolbuffers/protobuf/blob/v3.12.0/docs/implementing_proto3_presence.md

**Comment by 3ventic** [comment]
@Solution Could you follow the license agreement in the [pull request template](https://github.com/twitchtv/twirp/blob/master/.github/PULL_REQUEST_TEMPLATE.md)? We'll try to have this reviewed in the coming weeks.

**Comment by Solution** [comment]
@3ventic ofc, i'll do that.

**Comment by marioizquierdo** [comment]
There's an upcoming update with #304 to update to Protobuf APIV2. That will cleanup all the dependency updates that were done in this branch.

Could you isolate the changes needed to support the OPTIONAL feature flag in Twirp after the update to Protobuf APIV2 update is made?

**Comment by marioizquierdo** [comment]
Closing this. The [v8.0.0 release](https://github.com/twitchtv/twirp/releases/tag/v8.0.0) adds support for Protobuf APIv2 which allows Twirp services to use new features introduced on new versions of Protobuf for Go. LMK if there's anything else I'm missing. Thanks!

**Pull request closed without merging**
